bounswe/bounswe2022group9

- practice-app/README.md
- practice-app/event_app/templates/home.html
- practice-app/event_app/templates/viewGithubInfo.html
- practice-app/event_app/urls.py
- practice-app/event_app/views.py
- practice-app/requirements.txt
* User's can enter an gitHub username and see the information about it now.
* Two function for viewing github information are added to views.py
* viewGithubInfo.html is added
* New requirement is added to requirements.txt. To get the api response, I used requests module.
> Adding github information function

- practice-app/event_app/templates/sign_up.html
- practice-app/event_app/urls.py
- practice-app/event_app/views.py
* User's can now sign up to the web application.
* sign_up functions is added to views.py
* sign_up.html is added
> Adding sign up functionality

- practice-app/event_app/forms.py
- practice-app/event_app/templates/home.html
- practice-app/event_app/templates/universityFormPage.html
- practice-app/event_app/templates/universityShowPage.html
- practice-app/event_app/urls.py
- practice-app/event_app/views.py
Added a functionality to show universities by country name given by user.
> show universities functionality

- practice-app/event_app/templates/home.html
- practice-app/event_app/templates/viewActivity.html
- practice-app/event_app/urls.py
- practice-app/event_app/views.py
- Users can click on View Random Fun Activities link to get a random activity from an external api called Bored Api. 
- A function for viewing a random activity is added to views.py
- viewActivity.html is added
- To get the api response, I used requests module.
> Adding random fun activities functionality

- practice-app/event_app/templates/home.html
- practice-app/event_app/templates/view_subject_info.html
- practice-app/event_app/urls.py
- practice-app/event_app/views.py
* Users can now enter a subject to get a summary about it.
Closes #139
> Adding information about subject functionality

- practice-app/event_app/forms.py
- practice-app/event_app/templates/AddEducationFormPage.html
- practice-app/event_app/templates/ShowEducationPage.html
- practice-app/event_app/templates/home.html
- practice-app/event_app/urls.py
- practice-app/event_app/views.py
- practice-app/src/create_db.py
2 new related functionalities are added.
One is for users to add their education histories.
Other functionality shows education histories that users added.
There is no conflicts.
> adding and showing education history functionality is added

- practice-app/.gitignore
- practice-app/event_app/tests/test_views.py
- practice-app/event_app/views.py
- practice-app/github_api/admin.py
- practice-app/github_api/apps.py
- practice-app/github_api/models.py
- practice-app/github_api/serializer.py
- practice-app/github_api/tests.py
- practice-app/github_api/urls.py
- practice-app/github_api/views.py
- practice-app/requirements.txt
- practice-app/src/settings.py
- practice-app/src/urls.py
* Adding a new app called github api
* Views.py serializer.py and models.py are added.
* Requirements are updated
> Adding Github Api

- practice-app/event_app/templates/viewActivity.html
Added links for going back to home page and getting another random activity.
> back and another links added

- practice-app/.gitignore
- practice-app/src/urls.py
- practice-app/summary_api/admin.py
- practice-app/summary_api/apps.py
- practice-app/summary_api/models.py
- practice-app/summary_api/tests.py
- practice-app/summary_api/urls.py
- practice-app/summary_api/views.py
An API that supports GET and POST methods and returns in JSON format was added for the subject summary functionality.
Closes #200
> Add API for wikipedia summary

- art-community-platform/mobile/screens/Login/Signup.js
I have completed the signup page design features
> [Mobil] Feature/signup

- art-community-platform/backend/.gitignore
- art-community-platform/backend/app/user/tests/test_urls.py
- art-community-platform/backend/app/user/tests/test_views.py
- art-community-platform/backend/app/user/urls.py
- art-community-platform/backend/app/user/views.py
- art-community-platform/backend/docker-compose-deploy.yml
- art-community-platform/backend/docker-compose.yml
Login feature implemented in backend.
Changes:
> [Backend] Login

- art-community-platform/mobile/screens/Login/LoginNavigator.js
- art-community-platform/mobile/screens/Login/Signup.js
- art-community-platform/mobile/screens/Login/TermsAndConditions.js
Terms and Privacy Policy page should be readable before Signup operation . In this pull request you can see that this navigation is handled . You can test it by clicking Terms and Privacy Policy on the signup page.
> [Mobil] Feature/privacy policy

- art-community-platform/mobile/screens/Login/Login.js
- art-community-platform/mobile/screens/services/LoginServices.js
Backend connection for login operation has been implemented successfully. You can log in to the application with the status 200 successful responses, an alarm text is displayed with the 400 unsuccessful status responses and you cannot log in.
> [Mobile] Feature/login backend

- art-community-platform/mobile/screens/Profile.js
While preparing the profile page, the number of posts was displayed incorrectly. Since it is a mock page, it fixed manually , because profile page and backend are not connected right now.
> Post number is corrected

- art-community-platform/backend/app/api/urls.py
- art-community-platform/backend/app/api/views/homepage.py
I have implemented endpoint for getting homepage of a user which contains art items posted by his/her followings.
> Homepage of user implemented

- art-community-platform/backend/app/api/urls.py
- art-community-platform/backend/app/api/views/user.py
Added get_profile_info endpoint. The endpoint accepts GET requests. Takes a path variable (user id). Returns the user's:
* id
* username
* email
* birthdate
* name
* art items
* number of followers
*  number of following
* profile image url
*  location
*  password
> added "get_profile_info" endpoint

- art-community-platform/backend/app/api/urls.py
- art-community-platform/backend/app/api/views/art_item.py
- art-community-platform/backend/app/api/views/comment.py
- art-community-platform/backend/app/api/views/favourite.py
- art-community-platform/backend/app/api/views/follow.py
- favouriting an art item implemented.
- commenting on an art item implemented.
> favourite comment features

- art-community-platform/backend/app/api/helpers/user_helpers.py
- art-community-platform/backend/app/api/views/art_item.py
- art-community-platform/backend/app/api/views/homepage.py
- art-community-platform/backend/app/api/views/user.py
- Art items of user sorted
- Comments of art item sorted
> response lists sorted

- art-community-platform/backend/app/api/urls.py
- art-community-platform/backend/app/api/views/art_item.py
- Get all art items method implemented.
- Art items will be filtered and recommended to each user specifically.
> Feature Recommendation

- art-community-platform/backend/app/api/urls.py
- art-community-platform/backend/app/api/views/searchUser.py
I have implemented a search engine for a user
> Search Engine For a User

- art-community-platform/backend/app/api/helpers/user_helpers.py
Added a new helper function to prepare an infrastructure to the unfollow endpoint. The new helper function does:
* Checks whether users with given ids exists (follower and followed users are valid users)
* Checks whether user with given ids followes (follower follows followed or not -  this is done to validate the request)
* Deleting follower from the followers list of followed user
> Unfollow helper function - deleting follower from followers list of followed user

- art-community-platform/backend/app/api/urls.py
- art-community-platform/backend/app/api/views/search.py
I have implemented a search engine for Art Items.
> Search art item

- art-community-platform/backend/app/api/helpers/user_helpers.py
Added a new helper function to prepare an infrastructure to the unfollow endpoint. The new helper function does:
* Checks whether users with given ids exists (follower and followed users are valid users)
* Checks whether user with given ids followes (follower follows followed or not -  this is done to validate the request)
* Deleting followed user from the followings list of follower user
> Delete user from followings list function

- art-community-platform/backend/app/api/urls.py
- art-community-platform/backend/app/api/views/search.py
I have implemented search engine for exhibitons
> Search exhibition

- art-community-platform/backend/app/api/helpers/user_helpers.py
I have implemented various helper functions.
> Enhancement of helpers

- art-community-platform/backend/app/api/views/user.py
I have enhanced the api by adding count numbers of followers, followings, and art items of a specific user.
> Count numbers Added

- art-community-platform/backend/app/api/helpers/art_item_helpers.py
- art-community-platform/backend/app/api/views/art_item.py
- art-community-platform/backend/app/api/views/profile.py
- We will be expecting both img_str and img_url fields from client side. Img_str is for base64 encoded image and img_url is for the images uploaded on client side and its respective url to be saved on database.
- I need a fast merge to deploy the app before last day.
> image upload fields changed

- art-community-platform/backend/app/api/tests/test_auth.py
- art-community-platform/backend/app/api/tests/test_profile.py
- art-community-platform/backend/app/api/tests/test_unfollow.py
- art-community-platform/backend/app/api/tests/test_urls.py
- art-community-platform/backend/app/api/views/profile.py
- art-community-platform/backend/app/api/views/user.py
Both url tests and view tests are added, related to endpoints implemented by me.
> Unit Tests

- deliverables/CMPE451_Customer_Presentation_Milestone_2/individual_contributions_reports/Yagmur_Goktas.md
This is a pull request of the changes in Yağmur Göktaş's individual report. Created for second milestone deliverables.
> Individual report

- art-community-platform/backend/app/api/admin.py
- art-community-platform/backend/app/api/models/annotation.py
- art-community-platform/backend/app/api/serializers/serializers.py
- art-community-platform/backend/app/api/views/annotation.py
As we mentioned in issue #495  and #496, we made a research on W3C protocol and we designed some models for annotations. This commit includes the model for annotations and GET endpoints. Later, we will implement other endpoints as well.
DONE:
- The annotation model is created with  the fields below:
- art item id, owner id and annotation in json LD format.
- GET endpoint is added in annotations.py
- Serializer is updated according to the model.
> [Backend] Annotation Model

- art-community-platform/backend/app/api/views/art_item.py
- art-community-platform/backend/app/api/views/auth.py
- art-community-platform/backend/app/api/views/image_upload.py
- art-community-platform/backend/app/api/views/tag.py
- art-community-platform/backend/app/api/views/user.py
- art-community-platform/backend/requirements.txt
Deadline: 24.12.2022 23.59
Image upload functionality was not working properly as mentioned in issue #505. Therefore, create_art_item() method is updated in art item file. After this fix, frontend and mobile teams will post request to upload image.
DONE:
- create_art_item() method is updated.
- requirements are updated.
- now, cloudinary is used to host images.
> [Hotfix] Image Upload

- art-community-platform/backend/app/api/helpers/notification_helpers.py
- art-community-platform/backend/app/api/helpers/user_helpers.py
- art-community-platform/backend/app/api/tests/test_notification.py
- art-community-platform/backend/app/api/urls.py
- art-community-platform/backend/app/api/views/art_item.py
- art-community-platform/backend/app/api/views/comment.py
- art-community-platform/backend/app/api/views/exhibition.py
- art-community-platform/backend/app/api/views/favourite.py
- art-community-platform/backend/app/api/views/follow.py
- art-community-platform/backend/app/api/views/notification.py
- art-community-platform/backend/app/api/views/recommend.py
I coded to notifiy users when:
* the user is followed by another user
* one of the art items of the user is commented by another user
* one of the art items of the user is added to favorites of another user
* users followed by the user shares art items
* users followed by the user starts exhibitions
Also:
* Created a Django model for notifications (fields should be "notified_user_id", "notification_message")
* When one of the items above happened, store a new notification event in the database
* Implement a new endpoint called "notify", this endpoint should return notifications needed to be sent to the users.
In addition, there was a small bug in unfollow (when user id is sent as a string, server error was occurring), I handled it.
> Notifications

- art-community-platform/backend/app/api/tests/test_recommend_users
I have written unit tests for user recommendations
> Unit test recommend

- art-community-platform/mobile/screens/Exhibitons.js
- art-community-platform/mobile/screens/Home.js
- art-community-platform/mobile/screens/Settings.js
- art-community-platform/mobile/screens/services/GeneralServices.js
Settings page is connected to the backend
> [Mobile] Settings page backend connection

- art-community-platform/mobile/package.json
- art-community-platform/mobile/screens/Login/Signup.js
- art-community-platform/mobile/screens/Login/_tests_/Signup.test.js
Navigation test on signup screen
> signup test
